Добавляет моковые данные фильмов
htmlacademy-react/1084415-what-to-watch-5 pull request #5
Opened 2020-11-01 15:48 UTC by oderzhanie

2020-11-01 15:52 UTC, oderzhanie commented on src/components/app/app.jsx
> +  // const {films} = props;
В задании сказано, что моковые фильмы передавать нужно в файл Main. Значит, App не должен их получать в пропсах?

2020-11-01 15:55 UTC, oderzhanie commented on src/components/main/main.jsx
> +import {MoviesList} from "../movies-list";
Консоль выдает ошибку о том, что Main не может найти модуль MoviesList. Не смогла понять, почему.

2020-11-01 15:59 UTC, oderzhanie commented on src/components/movies-list/movies-list.jsx
> +  }
В учебном проекте сделано не так, но как воспроизвести их способ тут не поняла. И что именно должно быть в стейте - тоже. Я могу в стейте просто флаг апдейтить, а не сам элемент (фильм) хранить? (Не поняла, собственно, а как его хранить там, чтобы дальше использовать можно было).

2020-11-01 16:00 UTC, oderzhanie commented on src/components/movies-list/movies-list.jsx
> +        ))}
И вот это верная конструкция или нет?

2020-11-01 16:01 UTC, oderzhanie commented on src/components/movies-list/movies-list.jsx
> +  SmallMovieCard: PropTypes.objectOf(SmallMovieCard).isRequired, // Нужен проп на компонент?
Нужна ли валидация пропсов для импортируемого компонента?

2020-11-01 16:04 UTC, oderzhanie commented on src/components/small-movie-card/small-movie-card.jsx
> +    const {film, key, isCardActive} = this.props; // isActive тоже через пропсы передается?
Вот тут я не поняла: передавать сбда колбэк onCardHover (который меняет стейт флага isCardActive) или сам isCardActive можно передать? (мне же только флаг нужен тут в итоге?)

2020-11-01 16:53 UTC, ElseeCCD requested changes

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/app/app.jsx
> +  // const {films} = props;
Не нашла такого в задании, зато нашла такое:
Подключите созданные моки в index.js. Передайте их в виде props основному компоненту приложения (App). Не забудьте добавить с помощью пакета PropTypes валидацию props для App.

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/main/main.jsx
> +import {MoviesList} from "../movies-list";
Убираем скобочки, у нас не именованный экспорт )

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/main/main.jsx
> +  }).isRequired
эта структура еще не раз будет использоваться ) поэтому советую вынести кужа-нибудь в константу
```
export const FILM_SHAPE = {
    movieId: PropTypes.number.isRequired,
    movieName: PropTypes.string.isRequired,
    moviePoster: PropTypes.string.isRequired,
    movieRating: PropTypes.number.isRequired,
    movieRatingVerbal: PropTypes.string.isRequired,
    movieShortDescription: PropTypes.string.isRequired,
    movieGenre: PropTypes.string.isRequired,
    movieRuntime: PropTypes.number.isRequired,
    movieReviews: PropTypes.array.isRequired,
    movieDirector: PropTypes.string.isRequired,
    movieActors: PropTypes.array.isRequired,
    movieReleaseDate: PropTypes.number.isRequired,
    movieFullDescription: PropTypes.string.isRequired,
    movieVideo: PropTypes.string.isRequired,
    isMyList: PropTypes.bool.isRequired
  }
```
а тут уже использовать просто `film: PropTypes.shape(FILM_SHAPE).isRequired`

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +      isCardActive: false // В стейте компонента должна быть активная карточка с фильмом или можно так?
храни лучше id фильма )

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +  }
храни пока только id ) Кажется, оживлять в этом задании еще не нужно )

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +        ))}
к toString можно не приводить, id обычно и так строки ) Лучше моки подправь, если там не так )
Конструкция верная )

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +  films: PropTypes.array(PropTypes.shape({
Вот, собсвенно, тут уж наша константа и пригодится снова )

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/small-movie-card/small-movie-card.jsx
> +    const {film, key, isCardActive} = this.props; // isActive тоже через пропсы передается?
это промофильм же, т.е. примерно такой же компонент, как карточка фильма. Передавай пока только функцию, которая должна по наведению отрабатывать и менять активный фильм

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/small-movie-card/small-movie-card.jsx
> +    const actualClassName = isCardActive ? `small-movie-card:hover catalog__movies-card` : `small-movie-card catalog__movies-card`;
🤔 `:hover` самостоятельный и добавляется автоматически при наведении )

2020-11-01 16:53 UTC, ElseeCCD commented on src/components/small-movie-card/small-movie-card.jsx
> +  film: PropTypes.shape({
о, снова )

2020-11-23 17:47 UTC, ElseeCCD requested changes

2020-11-23 17:47 UTC, ElseeCCD commented on src/components/add-review-page/add-review-page.jsx
> +    // То есть стейт обновляется, а рендерятся измененения только при следующем onChange
Ты чуть-чуть неправильно обрабатываешь смену аттрибута checked. Т.е. тут отрабатывает всё корректно, стейт ставится, аттрибут убирается. Но потом выполняется функция render, а там у тебя checked стоит у инпута со значением 3 ) Звездочка в нужном месте отображается только когда ты 2 раза на одну и ту же кликаешь, потому что стейт не меняется, ререндер не выполняется )
Тебе нужно отсюда убрать всё, что ты написала в if ) Со сменой checked чудесно справится css, тебе необязательно проставлять его ручками, достаточно того, что храниться будет в state. У звездочки по дефолту смени `checked` на `defaultChecked`:
```
<input
   onChange={(evt) => {
     this.handleFieldChange(evt);
   }}
   className="rating__input" id="star-3" type="radio" name="rating" value="3" defaultChecked />
```

2020-11-23 17:47 UTC, ElseeCCD commented on src/components/add-review-page/add-review-page.jsx
> +                }}
evt не надо передавать руками, он автоматом во все слушатели передается, если нет других параметров, достаточно написать: 
`onChange={this.handleFieldChange}`

2020-11-23 17:47 UTC, ElseeCCD commented on src/components/add-review-page/add-review-page.jsx
> +                }}
тут для всех надо поправить onChange

2020-11-23 17:47 UTC, ElseeCCD commented on src/components/add-review-page/add-review-page.jsx
> +              }}
и тут тоже onChange

2020-11-23 19:38 UTC, ElseeCCD approved these changes

2020-11-23 19:39 UTC, merged