Добавляет HOC для проигрывания видео
htmlacademy-react/1084415-what-to-watch-5 pull request #6
Opened 2020-11-24 19:20 UTC by oderzhanie

2020-11-24 19:26 UTC, oderzhanie commented on src/components/video-player/video-player.jsx
> +    const {movieId, moviePreviewImg, moviePreviewLink, isPlaying, onMouseOver} = this.props;
VideoPlayer не получает ссылки на видео и картинку через пропсы:
Warning: Failed prop type: The prop `moviePreviewLink` is marked as required in `VideoPlayer`, but its value is `undefined`.

Не могу сама понять, где они теряются.

2020-11-25 20:10 UTC, ElseeCCD requested changes

2020-11-29 12:53 UTC, ElseeCCD approved these changes

2020-11-29 12:53 UTC, ElseeCCD commented on src/components/video-player/video-player.jsx
> +      clearTimeout(this.timerId);
в целом ок ) Но не пробовала просто onMouseOver и onMouseOut перенести сюда, а не в HOC обрабатывать? )

2020-11-29 12:53 UTC, ElseeCCD commented on src/components/tabs/tabs.jsx
> +    return <ActiveReviews />;
тут каждый таб в отдельный компонент надо будет вынести )

2020-11-29 12:53 UTC, merged